### ISSUE TITLE
daf-ethr-did implement import/exportIdentity

### ISSUE THREAD

**Issue by rado0x54** [uport-project/veramo#105]
Hey,

we would have a use-case to initialize the identity store with a reproducibly same key/identity, but currently the methods `importIdentity` and `exportIdentity` are not implemented on `daf-ethr-did`. Would the export Format just be a string of an encoded private Key or contain any other information?

If there is another way to initialize daf with a consistent identity, that would also help as a workaround.

Also there is a minor typo in the `AbstractIdentityProvider`:
```
  exportIdentity(did: string): Promise<string> {
    return Promise.reject('Method importIdentity not implemented')
  }
```

**Comment by simonas-notcat** [comment]
@rado0x54 `daf identity-manager --import` and `daf identity-manager --export`

**Comment by rado0x54** [comment]
Thanks, I'll have a look.!

**Comment by rado0x54** [comment]
Hey @simonas-notcat, in my mind the `importIdentity` should not require the `identityProviderType` if that is part of the export. Furthermore, the export provider string is not the one required. So there must be some discrepancy in the code.
Export: `"provider":"rinkeby-ethr"`
Required: `rinkeby-ethr-did`
e.g. this code did not work for me because of that.
```
      let jsonIssuerConfig = JSON.parse(process.env.ISSUER_IDENTITY);
      await core.identityManager.importIdentity(jsonIssuerConfig.provider, process.env.ISSUER_IDENTITY);
```
So either don't export the provider or don't require it on import.

**Comment by rado0x54** [comment]
Closing issue, since it was superseded by code changes.
