### ISSUE TITLE
[bug] @veramo/key-manager - SES_IMPORT_REJECTED

### ISSUE THREAD

**Issue by luckdev01** [uport-project/veramo#1090]
I encountered this issue when using @veramo/key-manager.
[SyntaxError: Possible import expression rejected at <unknown>:44396. (SES_IMPORT_REJECTED)]

Related issue: https://github.com/endojs/endo/blob/master/packages/ses/error-codes/SES_IMPORT_REJECTED.md

The issue is due to this.
![image](https://user-images.githubusercontent.com/40633197/209845037-e0b2c716-d9c8-41e6-8531-a28aa1a0b1d8.png)
The problem is that the function name is "import".

**Comment by nickreynolds** [comment]
@mirceanis this does seem like it could be causing problems. I propose we just rename this function to `importKey`. Should we rename the other functions to match?

**Comment by mirceanis** [comment]
Correct. I'll work on it today so that we can include it in the upcoming 5.0 release
