### ISSUE TITLE
While resolving did's this error occurs in veramo for react-native

### ISSUE THREAD

**Issue by Musa00789** [uport-project/veramo#1094]
Possible Unhandled Promise Rejection (id: 1):
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)

**Comment by nickreynolds** [comment]
Hi @Musa00789 , can you confirm if you have set your Infura Project ID in `setup.ts`? I am reproducing your error if I do not set the project ID. A functioning example can be found here: https://github.com/veramolabs/veramo-react-native-tutorial

If you would like to share a link to a repository or other code sample that reproduces the issue, I could take a look at it.

**Comment by Musa00789** [comment]
Hi @nickreynolds, Thank you for your help. The infura key you mentioned was not added. Thanks to you the error is resolved.
