### ISSUE TITLE
Downgrade typeorm to 0.2.24

### ISSUE THREAD

**Issue by roderik** [uport-project/veramo#165]
There is an issue with 0.2.25 in browser builds: https://github.com/typeorm/typeorm/issues/6110

It is fixed but no new release yet.

**Comment by jasonhealy** [comment]
Daf currently uses 0.2.24 of [TypeOrm](https://github.com/uport-project/daf/blob/master/packages/daf-core/package.json#L14)

**Comment by devrajsinghrawat** [comment]
Yes we faced the issue when used v0.2.25 and faced error `TypeError: Right-hand side of 'instanceof' is not an object` 

when investigated then found that daf-core is still using v0.2.24

**Comment by roderik** [comment]
It uses `"typeorm": "^0.2.24"` which means >= 0.2.24 <0.3.0 according to https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

I personally prefer exact versions since maintaining 100% safe upgrading even in patch releases is not a given.

**Comment by roderik** [comment]
btw, when using `yarn` put this in your (top level) package.json to force it to 0.2.24

```
  "resolutions": {
    "typeorm": "0.2.24"
  }
```
