### ISSUE TITLE
TODO: implement `addService` / `removeService` for web-did controller

### ISSUE THREAD

**Issue by mirceanis** [uport-project/veramo#172]
The identity store should be able to handle extra fields, like service entries required for DID docs.

https://github.com/uport-project/daf/blob/989720281c3159aee656ee1098cb507aa10ce218/packages/daf-web-did/src/identity-controller.ts#L22

I imagine something along these lines would work:
```
let serializedIdentity = await this.identityStore.get(this.did)
serializedIdentity.services.add(service)
await this.identityStore.set(serializedIdentity)
```

This needs to be paired with some code to list the added services in `getDidDocument()`

**Comment by simonas-notcat** [comment]
@mirceanis I was also thinking about this, but went with a simpler solution for now. Here is an example: https://github.com/uport-project/daf/blob/master/examples/web-did/index.ts#L24

**Comment by mirceanis** [comment]
That works great as an example but I imagine many would want their DID doc changes signed for auditability or maybe spoof protection so it makes sense to abstract adding and removing service endpoints behind their intended API.

Signing a `did:web` document change is not in the scope of this ticket, but having this functionality there would allow the signing functionality to be implemented.
