### ISSUE TITLE
Filters not working for `identities`

### ISSUE THREAD

**Issue by ajunge** [uport-project/veramo#204]
The following GraphQL query returns all the identities

```
query {
  identities(input: { where: { column: did,  value: "asd"} }) {
    did
    saveDate
  }
}
```

I think the problem is here:  https://github.com/uport-project/daf/blob/master/packages/daf-core/src/graphql/graphql-core.ts#L331

The `find` method accepts other form of filters.

**Comment by simonas-notcat** [comment]
GraphQL support removed
