### ISSUE TITLE
Generating an Identity from supplying external seed phrase

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/veramo#232]
Dear Team,

Currently we create identity (key-pair) using daf-core identity manager by providing type of Identity Provider.

But if someone whats to create the identity using pre decided seeds then how does Daf supports in that.

Regards
Dev

**Comment by mirceanis** [comment]
At this moment, that is not possible out of the box.
We plan to write a new identity manager plugin that will support this, but it will not be available in DAF 7.0, but perhaps the next feature release (like 7.1).

**Comment by ilanolkies** [comment]
Hey! We have built a superset of DAF for this. Wanna check the lib?
https://github.com/rsksmart/rif-identity.js/tree/develop/packages/rif-id-daf
