### ISSUE TITLE
daf-react-native-libsodium library from_hex / to_hex is not a function.

### ISSUE THREAD

**Issue by jessgusclark** [uport-project/veramo#237]
The RIF team is working with the uPort DAF in React Native and trying to implement secretBox with the `daf-react-native-libsodium` library.

We are running into the following error when storing information to the database:

```
react_native_sodium_1.default.from_hex is not a function
```

This error happens on `secretbox.encrypt`. [This line here](https://github.com/uport-project/daf/blob/master/packages/daf-react-native-libsodium/src/secret-box.ts#L22).

We are implementing secretBox from `daf-react-native-libsodium` with the this code:

```
import { KeyManagementSystem, SecretBox } from 'daf-react-native-libsodium'

...

const secretBox = new SecretBox('29739248cad1bd1a0fc4d9b75cd4d2990de535baf5caadfdf8d8f86664aa830c')
const keyStore = new Daf.KeyStore(dbConnection, secretBox)
```

There is an example of the error with this repo/branch: https://github.com/jessgusclark/rif-identity-daf-mini/tree/secretBox-demo
The implementation of secretBox is located here: https://github.com/jessgusclark/rif-identity-daf-mini/blob/secretBox-demo/setup.js#L26-L28

The dependency for `react-native-sodium` does not include the exports for `to_hex` or `from_hex`. Those exports are located here: https://github.com/lyubo/react-native-sodium/blob/master/index.d.ts

How did you get the  `daf-react-native-libsodium`'s implementation of secretBox to work with `react-native-sodium`?

Thank you.

**Comment by jasonhealy** [comment]
SecretBox encryption is not supported in react native in its current iteration because the encryption key would need to be stored on the device so defeats the purpose of encrypting it.

**Comment by ilanolkies** [comment]
Hi @jasonhealy! The `SecretBox` has no purpose in `daf-react-native-libsodium`?
