### ISSUE TITLE
How to update the VC/VP, which is already store in the local db?

### ISSUE THREAD

**Issue by rizwanzaheer** [uport-project/veramo#254]
Right Now, I'm saving the VC/VP in the local database but after certain time period, I want to modify the existing VC/VP based upon the the query but I didn't find any solution/way to update the VP/VC
please advice

**Comment by simonas-notcat** [comment]
It is not possible to update a VC/VP. You need to create a new one.

**Comment by rizwanzaheer** [comment]
@simonas-notcat ok
What about the delete VC/VP?
