### ISSUE TITLE
DIDs: alsoKnownAs property

### ISSUE THREAD

**Issue by nikolockenvitz** [uport-project/veramo#260]
The `alsoKnownAs` property has been added to the DID spec recently.
It's basically a string array of some identifiers (URIs) by which the DID subject can also be identified. (see the [corresponding section in w3c did-core](https://w3c.github.io/did-core/#alsoknownas))

I was wondering whether it is planned to include that in daf-ethr-did too?

**Possible implementation**
Could be done building upon the `setAttribute` method of the ethr-did-registry, e.g. `did/aka` + hex encoded string.
Similar to the other methods in daf-ethr-dids identity-provider (beta-branch) it would just be something like `async addAlsoKnownAs({ identity, service, options }: { identity: IIdentity; alsoKnownAs: string; options?: any }, context: IContext): Promise<any>`

What's your opinion on that?
(Should I also mention that in `ethr-did-resolver` somehow?)

Do you have an estimation when the beta-branch will be merged? (Thinking about whether it makes sense to include that in the current version or just go for beta-branch).

**EDIT**: maybe someone could remove the bug label and add something like feature or feature-request...

**Comment by mirceanis** [comment]
Thanks for flagging this.
That sounds like a good proposal and it would be fairly easy to add to daf-ethr-did.
However, the resolver would also need to be updated to support this new attribute type.
Let's agree on a format for the `did/aka` entries in [ethr-did spec](https://github.com/decentralized-identity/ethr-did-resolver/blob/master/doc/did-method-spec.md) first and then it would need to be implemented in daf and ethr-did resolver simultaneously for it to work.

**Comment by nikolockenvitz** [comment]
Still an open issue that should be worked on IMO

**Comment by mirceanis** [comment]
> Still an open issue that should be worked on IMO

Yes, it is. We're waiting for the DID spec to become a bit more stable before committing to this.
