### ISSUE TITLE
Support of JSON-LD Signature Proofs

### ISSUE THREAD

**Issue by rado0x54** [uport-project/veramo#273]
In addition to the currently supported JWT-based Verifiable Credentials, DAF should add native support for JSON-LD Signature Proofs.
An existing JS-based implementation can be found at [Digital Bazaar](https://github.com/digitalbazaar/vc-js).

In order to provide a generalized implementation of Verifiable Credential Use-Cases, the Veramo Core needs to provide three generic interfaces around Credential Handling:

1. Issue of Verifiable Credentials: As an Issuer I want to be able to create and sign Verifiable Credentials.

2. Verification of Verifiable Credentials (as a Holder)
As a Holder I need to proof the correct issuance of a Verifiable Credential. Furthermore, the Holder needs to be able to verify an updated Credential Status at any time. Lastly, on more complicated ZKP Proofing Schemes, the holder needs to verify the they are able to generate Verifiable Presentations.

3. Verification of Verifiable Presentation (as a Verifier)
As a Verifier I need to be able to proof the Validity of a Verifiable Presentation. This compounds:
- Correct Schema / Dataformats
- Correct Signature associated with a given Issuer
- Correct Signature associated with a given Holder (Holder binding)
- Unrevoked CredentialStatus
- Advanced: Trust Relationship to Issuer (Policy)
- Advanced: Trust Relationship to Holder (Policy)

2 and 3 might be combined into a unfied verification API.

For all use cases, the following credential formats and signature schemes need to be supported:
1. JWT Format with JWS Signature
2. JSON-LD Format with JSON-LD Proof Signature with the following signature suites:
a) EcdsaSecp256k1Signature2019
b) BbsBlsSignature2020 (separate Epic)

**Comment by awoie** [comment]
IMO, this will require at least the following:

1. Adding ld-proofs to ICredentialIssuer interface
2. Adding ld-proofs to KeyManager interface
3. Adapt CredentialIssuer to validate `@context`
4. Adapt W3cMessageHandler to validate `@context`
5. Adapt DataStore API for `@context` management
6. Adding `verification-method` / `kid` to CredentialIssuer to support multiple signing/verification keys per DID
7. Based on 5, adapt CredentialIssuer to support ld-proof variations (`issuer` or `verification-method` might contain the DID)
8. Implement ld-proof interfaces on the KMS level (for Ed25519/Secp256k1)

**Comment by rado0x54** [comment]
This epic covers signature creation and verification on VC and VP and therefore relates to https://github.com/uport-project/veramo/issues/375 directly.
