### ISSUE TITLE
Support for well-known DID Configuration

### ISSUE THREAD

**Issue by rado0x54** [uport-project/veramo#274]
Support the official standard of binding traditional domain names (DNS) to decentralized identifiers (DID). Spec: https://identity.foundation/.well-known/resources/did-configuration/

**Comment by mirceanis** [comment]
We need to detail this better.
@rado0x54 @italobb please define a scope for this plugin.

**Comment by italobb** [comment]
@mirceanis @rado0x54 Actually, I have already implemented that support with this plugin: https://github.com/SertoID/veramo-plugin-did-config

Today the plugin is capable of creating the DID configuration file from a list of DIDs owned by the agent and verify the well-known DID configuration from a web domain.

**Comment by mirceanis** [comment]
That's great!
I think it should be migrated to use the `@veramo/` scope. Do you have any plans for that?
I believe that if you one tries to mix `daf-*` and `@veramo/*` packages in the same typescript project it will not build.

**Comment by italobb** [comment]
@mirceanis There's a branch called `veramo` where the plugin was already migrated to use Veramo instead of DAF. I'm just waiting for the Baseline Hackathon to end before merging it (next week probably).

About migrating it to use `@veramo/` scope, please give me the instructions. Maybe I have already done something in the `veramo` branch, but would appreciate to have your support on that, please.

**Comment by mirceanis** [comment]
> About migrating it to use `@veramo/` scope, please give me the instructions. Maybe I have already done something in the `veramo` branch, but would appreciate to have your support on that, please.

Fantastic, @italobb!
I'll try to contribute some suggestions there.

**Comment by mirceanis** [comment]
This is missing some details. What actually needs to be implemented and where?

**Comment by mirceanis** [comment]
closing this since there is a plugin with this functionality: https://github.com/SertoID/veramo-plugin-did-config
