### ISSUE TITLE
veramo.io: Documentation of Veramo Flows

### ISSUE THREAD

**Issue by rado0x54** [uport-project/veramo#331]
Extend Documentation on veramo.io with various Howto Flows:

Guides
Publicly facing Veramo Youtube Channel for Integrated Video tutorials.
Show off diverse applications / configuration of veramo.
- CLI
- Hosted Deployment
- Mars UI (deprecated) -> Agent Explorer

**Comment by mirceanis** [comment]
@gbugyis, @jasonhealy, @awoie please link some smaller documentation tasks here.

ex: aws deployment, react-native config demo, ARIES agent article

**Comment by gbugyis** [comment]
AWS deployment is [over here](https://github.com/uport-project/veramo-website/issues/43).

**Comment by jasonhealy** [comment]
https://github.com/uport-project/veramo-website/issues
