### ISSUE TITLE
react-native after setup: "Can't find variable: ids"

### ISSUE THREAD

**Issue by trentlarson** [uport-project/veramo#337]
**Bug severity**
1

**Describe the bug**
After a clean install using react-native (from [these instructions](https://veramo.io/docs/guides/react_native)) and starting the app, there's an error at the bottom of the screen saying "Possible Unhandled Promise Rejection (id: 0):".

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow [these instructions](https://veramo.io/docs/guides/react_native).
2. Run `npx react-native run-ios`
3. See the error at the bottom of the mobile screen.

**Observed behaviour**
There's an error at the bottom.
   
**Expected behaviour**
No error.

**Details**

- Initial screen with error on the bottom:
<img width="387" alt="Screen Shot 2021-01-18 at 10 07 03 AM" src="https://user-images.githubusercontent.com/238296/104944772-efd93500-5974-11eb-94fd-9d54b0c01a09.png">

- Screen after clicking on that error:
<img width="387" alt="Screen Shot 2021-01-18 at 10 08 11 AM" src="https://user-images.githubusercontent.com/238296/104944951-375fc100-5975-11eb-972b-fc42bcdd91e6.png">

- Screen after clicking 'See More' on the top stack trace (and note that the bottom line is the end of the trace):
<img width="387" alt="Screen Shot 2021-01-18 at 10 08 22 AM" src="https://user-images.githubusercontent.com/238296/104944991-434b8300-5975-11eb-8296-0347fae5377e.png">

- Screen after clicking 'See 10 more frames' on the bottom under 'Call Stack':
<img width="387" alt="Screen Shot 2021-01-18 at 10 10 38 AM" src="https://user-images.githubusercontent.com/238296/104945221-9d4c4880-5975-11eb-82f2-e0370598daf5.png">

- Screen after scrolling down from that previous screen:
<img width="387" alt="Screen Shot 2021-01-18 at 10 10 55 AM" src="https://user-images.githubusercontent.com/238296/104945247-a3dac000-5975-11eb-9439-22915cf5fccd.png">

**Additional context**
I haven't yet tested on Android.

**Versions (please complete the following information):**
 - Veramo: 1.0.1
 - Browser: iOS simulator (iPhone 11)
 - Node Version: v12.13.1
 - Yarn Version: 1.22.4

**Comment by jasonhealy** [comment]
Try changing `console.log(ids)` to be `console.log(_ids)` or just remove the log.

**Comment by trentlarson** [comment]
Ah!  Thanks.  I just submitted a PR for that.

So I'm curious: how did you narrow it down to that line?  (I see the `console.warn` but it's hard to even tell if that's related.)
