### ISSUE TITLE
Issue when setting up Veramo agent in Node

### ISSUE THREAD

**Issue by jcaporossi** [uport-project/veramo#353]
**Bug severity**
5

**Describe the bug**
I have an error when installing sqlite3 (yarn add sqlite3)

**To Reproduce**
Steps to reproduce the behaviour:
1. mkdir veramo-agent && cd veramo-agent
2. yarn init -y
3. yarn add typescript ts-node --dev
4. yarn add @veramo/core @veramo/credential-w3c @veramo/data-store @veramo/did-manager @veramo/did-provider-ethr @veramo/did-provider-web @veramo/did-resolver @veramo/key-manager @veramo/kms-local ethr-did-resolver web-did-resolver
5. yarn add sqlite3

**Observed behaviour**
Error shown in console terminal
   
**Expected behaviour**
sqlite3 should be installed into node_modules/

**Details**
console output:

yarn add v1.22.10
[1/4] 🔍  Resolving packages...
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sqlite3 > node-gyp > request > har-validator@5.1.5: this library is no longer supported
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.15.2 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@14.15.2 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.2 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.2 | darwin | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jcaporossi/.node-gyp/14.15.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jcaporossi/.node-gyp/14.15.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/jcaporossi/.node-gyp/14.15.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.2 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/nothing.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/Users/jcaporossi/.nvm/versions/node/v14.15.2/bin/node" "/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3
gyp ERR! node -v v14.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jcaporossi/.nvm/versions/node/v14.15.2/bin/node /Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 20.2.0
node-pre-gyp ERR! command "/Users/jcaporossi/.nvm/versions/node/v14.15.2/bin/node" "/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.15.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/jcaporossi/.nvm/versions/node/v14.15.2/bin/node /Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/jcaporossi/Documents/uPort/veramo-agent/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Additional context**

**Versions (please complete the following information):**
 - Node Version 14.15.2

**Comment by gbugyis** [comment]
This is an issue with sqlite3 - the new version doesn't provide pre-built binaries for all the platforms and node versions. One way to resolve it is to install the previous version: `yarn add sqlite3@5.0.0` . Another option is to use a previous node version `13.9.0`, for example.

**Comment by jcaporossi** [comment]
Thanks Greg, no pb with sqlite@5.0.0 !
