### ISSUE TITLE
NPM Packages not built

### ISSUE THREAD

**Issue by BrianCraig** [uport-project/veramo#354]
**Bug severity**
3

**Describe the bug**
`daf-core`, `daf-message-handler`, `daf-did-jwt` and `daf-w3c` are not built on the last deploys on NPM. (Version 7.0.0)

**To Reproduce**
Steps to reproduce the behaviour:
1. run `npm install daf-core daf-message-handler daf-did-jwt daf-w3c`

**Observed behaviour**
2. Trying to use the libs is not working, because `.build/` files are not present
   
**Expected behaviour**
2. The libs should work fine

**Comment by gbugyis** [comment]
When DAF was released as Veramo, those packages were also renamed. They should be `@veramo/core`, `@veramo/message-handler`, `@veramo/did-jwt`, `@veramo/credential-w3c`. 

So: `npm install @veramo/core @veramo/message-handler @veramo/did-jwt @veramo/credential-w3c` should work.

**Comment by mirceanis** [comment]
@BrianCraig you are right, that is a mistake on our end; the `daf-*@7.0.0` packages were not packaged properly.

If you are not ready to adopt the new package layout, you can still use the daf packages by installing the `@beta` variants.

```bash
npm install daf-core@beta daf-message-handler@beta daf-did-jwt@beta daf-w3c@beta
```

Please let us know if this works for you.

**Comment by mirceanis** [comment]
Please reopen if the suggested fix does not work for you
