### ISSUE TITLE
[proposal] Support URL redirects in url-handler

### ISSUE THREAD

**Issue by rkreutzer** [uport-project/veramo#362]
Some applications use a URL shortener service to create QR Codes that are easier to scan. When fetching that URL, a 302 redirect returns the full URL that includes a JWT. 

The url-handler could be revised to compare the URL that was returned in the fetch command with the one submitted. If they are different, it could check if a JWT exists on the c_i query parameter of the returned URL.

**Comment by mirceanis** [comment]
Sounds good.
Do you want to try to implement this functionality, @rkreutzer ?

**Comment by rkreutzer** [comment]
I can do that.

**Comment by mirceanis** [comment]
Your PR to fix this is now merged.
It will be available in the next minor release.

In the meantime, you can use the `@next` release channel: `@veramo/url-handler@next`
Generally, it's best to use the same release with all your @veramo dependencies.
