### ISSUE TITLE
[proposal] Add guide about CLI configuration

### ISSUE THREAD

**Issue by mirceanis** [uport-project/veramo#382]
The CLI configuration loader is quite powerful but it also requires some documentation.

Some topics to cover:
* the basic options (agent, plugins, static context, ENV variables)
* referencing classes, functions, objects, and primitives
* installing and referencing external modules
* using relative paths
* [versioning?]

**Comment by simonas-notcat** [comment]
https://github.com/uport-project/veramo-website/pull/70
