### ISSUE TITLE
 Support challenge / domain replay protection flow [Veramo SDR]

### ISSUE THREAD

**Issue by rado0x54** [uport-project/veramo#385]
As a Veramo integrator, I would like a Selective Disclosure Request (SDR) to contain an optional challenge and domain string parameter, so that verifier has a strong binding of a Verifiable Presentation to a previously SDR. (Replay protection).

Acceptance Criteria
* An SDR can contain an optional string field "challenge" when being created.
* An SDR can contain an optional string field "domain" when being created.
* Verification of Verifiable Presentation (JWT-VC) supports challenge and domain parameters (already supported in did-jwt)
* validatePresentationAgainstSdr is updated to take challenge and domain verification into account.
(* former uport solution: Response (VP) contains the complete original request (SDR))
* Support a stateless challenge response model as well. (@rado0x54 Move into separate ticket)

**Comment by awoie** [comment]
@rado0x54 pls spec out more details, i.e., flows first.

**Comment by awoie** [comment]
for stateless, we could just do something like challenge=base64url(challenge, signature: base64url(sign(challenge))
