### ISSUE TITLE
Support LD Signature and Verification for EIP712 (TypedData)

### ISSUE THREAD

**Issue by rado0x54** [uport-project/veramo#422]
In order to better structured data signing with JSON-LD (e.g. Metamask and other Ethereum-based applications), Veramo should support the following proposal: https://uport-project.github.io/ethereum-eip712-signature-2021-spec/

Acceptance Criteria
- Able to create VC with and and EIP712 Signature Proof.
- Able to verify VC with an EIP712 Signature Proof.
- Support react web3 demos / tutorials for Metamask and Walletconnect (https://docs.walletconnect.org/json-rpc-api-methods/ethereum#eth_signtypeddata)

**Comment by rado0x54** [comment]
This relates to https://github.com/decentralized-identity/ethr-did-resolver/issues/107

**Comment by mirceanis** [comment]
closed by #899
