### ISSUE TITLE
TypeError: context.agent.dataStoreSaveVerifiableCredential is not a function

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/veramo#460]
**Bug severity**
5

**Describe the bug**
An exception is raised when calling agent.createVerifiableCredential. 

**To Reproduce**
Steps to reproduce the behaviour:

```
const verifiableCredential = await agent.createVerifiableCredential({
  credential: {
    issuer: { id: identity.did },
    credentialSubject: {
      username: username,
    },
  },
  proofFormat: 'jwt',
  save: true,
});
```

**Observed behaviour**
After facing the issue, tried to check all the samples at veramo.io but nothing seems to fix it. So, i checked the code at this repository and I noticed that sometime you add the method 'dataStoreSaveVerifiableCredential' to the agent at setup. But adding this method cased the error to disappear sometime and appear sometime. Which case more confusion to me.
    
**Expected behaviour**
Create VC without issues.

**Details**
Exception stack trace:
> TypeError: context.agent.dataStoreSaveVerifiableCredential is not a function
      at Object.<anonymous> (node_modules/@veramo/credential-w3c/src/action-handler.ts:260:29)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/@veramo/credential-w3c/build/action-handler.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Additional context**

```

export const agent = createAgent<
  IDIDManager &
    IKeyManager &
    Pick<
      IDataStore,
      | 'dataStoreSaveVerifiableCredential'
      | 'dataStoreSaveVerifiablePresentation'
    > &
    IDataStoreORM &
    IResolver
>({
  plugins: [
    new KeyManager({
      store: new KeyStore(dbConnection as any),
      kms: {
        local: new KeyManagementSystem(),
      },
    }),
    new DIDManager({
      store: new DIDStore(dbConnection as any),
      defaultProvider: 'did:web',
      providers: {
        'did:web': new WebDIDProvider({
          defaultKms: 'local',
        }),
      },
    }),
    new DIDResolverPlugin({
      resolver: new Resolver({
        web: webDidResolver().web as any,
        //resolve some other DID methods using the centralized `uniresolver.io` service
        key: uniResolver as any,
        elem: uniResolver as any,
      }),
    }),
    new CredentialIssuer(),
  ],
});
```

**Versions:**
 - Veramo: 1.1.0
 - Node Version: 12.13.0

Many thanks in advance,

**Comment by mirceanis** [comment]
Hi, @Muhammad-Altabba 
It looks like your agent is missing the data store plugins.
You need to add the `DataStore` plugin to the list.
```typescript
plugins: [
  //...
  new DataStore(dbConnection),
]
```
Also note that the type information provided to `createAgent` needs to match the capabilities of the plugins you use.
In your case, the types would look like this:
```typescript
agent = createAgent<
  IDIDManager &
    IKeyManager &
    IDataStore &
    IResolver
>({
  plugins: [
    //...
```

You can see an example here: https://github.com/uport-project/veramo/blob/7b47fe53e000c487cd9fb3595f35dd57eca57d31/__tests__/localAgent.test.ts#L132

I hope this helps. Please reopen this issue if the solution does not work.

**Comment by Muhammad-Altabba** [comment]
Thanks @mirceanis 
I added now the missed `new DataStore(dbConnection)` to the plugins. But still facing the same issue.

Here is the agent configuration I have now:
```
export const agent = createAgent<
  IDIDManager & IKeyManager & IDataStore & IDataStoreORM & IResolver
>({
  plugins: [
    new KeyManager({
      store: new KeyStore(dbConnection as any),
      kms: {
        local: new KeyManagementSystem(),
      },
    }),
    new DIDManager({
      store: new DIDStore(dbConnection as any),
      defaultProvider: 'did:web',
      providers: {
        'did:web': new WebDIDProvider({
          defaultKms: 'local',
        }),
      },
    }),
    new DIDResolverPlugin({
      resolver: new Resolver({
        web: webDidResolver().web as any,
        //resolve some other DID methods using the centralized `uniresolver.io` service
        key: uniResolver as any,
        elem: uniResolver as any,
      }),
    }),
    new CredentialIssuer(),
    new DataStore(dbConnection as any),
  ],
});

```

**Comment by mirceanis** [comment]
try to add `new DataStoreORM(dbConnection)` as well.

**Comment by Muhammad-Altabba** [comment]
Many thanks @mirceanis 
Actually adding `new DataStore(dbConnection as any)`, to the plugins, did the trick and no need to add `new DataStoreORM(dbConnection)` but I was using a cashed version of the file.
