### ISSUE TITLE
Implement MessageHandler for handling DIDCommV2 envelopes

### ISSUE THREAD

**Issue by awoie** [uport-project/veramo#469]
DIDCommV2 messages are identified by their cty and can have different forms:
- JWM (JWE) with ECDH-1PU --> needs to be decrypted with agents private key and needs to resolve public key of recipient
- JWM (JWS) with EdDSA/ES256K --> needs to be verified
- Plaintext

JWE and JWS are in JSON general serialization, NOT compact serialization

No threaded protocol support needed.

handleMessage should still emit the event validatedMessage in case everything went correctly

**Comment by mirceanis** [comment]
@awoie please track the JWS & plaintext cases separately

**Comment by awoie** [comment]
implemented but integration tests are missing: https://github.com/uport-project/veramo/blob/feat/add-didcomm-v2
