### ISSUE TITLE
GetThreads Agent Method

### ISSUE THREAD

**Issue by awoie** [uport-project/veramo#470]
The current message demo in Agent Explorer is surfacing a number of issues that should be handled by the server. We should aim to move as much business logic to the agent as possible.

### Problem
Retrieving metadata about the thread e.g which identifier is YOU, can this thread be trusted?, the names and profile information for the thread recipients (not YOU members), the last message including timestamps,

The proposed solution is to have **getThreads** + **getThreadByID** + **archiveThread** agent methods.

### getThreads (args: {...TBD })

```
 {
   threadId: 'STRING',
   members: [{ name: 'STRING', did: STRING, trusted: BOOLEAN }], // Can be group
   viewer: STRING, 
   status: 'STRING', -TBD eg 'TRUSTED | UNTRUSTED | PENDING',
   archived: BOOLEAN,
   lastMessage: MESSAGE,
   messageCount: NUMBER
 }
```

### getThreadByID (args: {threadId: 'STRING'})
```
[
 {
   threadId: 'STRING',
   members: [{ name: 'STRING', did: STRING, trusted: BOOLEAN }], // Can be group
   viewer: STRING, 
   status: 'STRING', -TBD eg 'TRUSTED | UNTRUSTED | PENDING',
   archived: BOOLEAN,
   lastMessage: MESSAGE
 }
]
```

### archiveThread (args: {threadId: 'STRING'})
```
 {
   threadId: 'STRING',
   members: [{ name: 'STRING', did: STRING, trusted: BOOLEAN }], // Can be group
   viewer: STRING, 
   status: 'STRING', -TBD eg 'TRUSTED | UNTRUSTED | PENDING',
   archived: BOOLEAN,
   lastMessage: MESSAGE,

 }
```

### Thread STATUS
TRUSTED - You have a valid Verifiable Profile for all of the members
PARTIALLY_TRUSTED - You have some valid Verifiable Profiles for all members
UNTRUSTED - You have no Verifiable Profiles for any member
PENDING - You have issued a Profile Request within a TIMEFRAME, after timeframe defaults back to previous STATUS if no change

**Comment by simonas-notcat** [comment]
@awoie it is already possible to get the same result using IDataStoreORM API:

```typescript
await agent.dataStoreORMGetMessages({
  where: [
    {
      column: "type",
      value: [ "urn:veramo.io/didcomm/v1/basicmessage" ]
    }
  ],
  order: [
    {
      column: "createdAt",
      direction: "DESC"
    }
  ]
})
```

**Comment by mirceanis** [comment]
if this is already done, please add a link to the relevant method

**Comment by awoie** [comment]
@jasonhealy pls check if this is all you need for the messaging demo, then close, otherwise create new tasks for the missing functionality. thx.

**Comment by awoie** [comment]
closing this issue since current api has support for this

**Comment by jasonhealy** [comment]
Reopening...

**Comment by jasonhealy** [comment]
Api spec doc
https://hackmd.io/ARfA07qUQvmGtd8SjIQYpw?both

**Comment by jasonhealy** [comment]
https://hackmd.io/ARfA07qUQvmGtd8SjIQYpw
