### ISSUE TITLE
Setup DIDCommV2 Messaging demo environment (phase 2)

### ISSUE THREAD

**Issue by awoie** [uport-project/veramo#472]
- Update Agent Explorer to support DIDComm V2 API.
- Have two hosted deployments use DIDComm V2 to communicate.

**Comment by awoie** [comment]
@jasonhealy pls detail scope

**Comment by jasonhealy** [comment]
Superseded by https://github.com/veramolabs/agent-explorer/issues/48 and https://github.com/veramolabs/agent-explorer/issues/49
