### ISSUE TITLE
Create UI for sending DIDCommV2 messages

### ISSUE THREAD

**Issue by awoie** [uport-project/veramo#473]
With local KMS

**Comment by awoie** [comment]
@jasonhealy pls detail scope (re phase 3)

**Comment by jasonhealy** [comment]
Support in Agent explorer

**Comment by jasonhealy** [comment]
- Setup public messaging application to live under `inbox.veramo.dev`
- Authenticate with MetaMask
- View my messages
- Compose messages

Additional:
- Add custom messaging endpoint
- Update DID doc
- Attach VerifiableCredentials
- Attach SelectiveDisclosureRequests (Request)
- Attach VerifiablePresentation (Response)

**Comment by awoie** [comment]
redundant issue

**Comment by awoie** [comment]
redundant issue
