### ISSUE TITLE
In order to debug `@veramo/did-jwt` with Visual Studio Code, the JavaScript code at did-jwt.js need to not be minified

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/veramo#501]
The code inside did-jwt.js file is minified, this made debugging the code very painful. I am using Visual Studio Code. And because the variable names is different than in the Typescript, the editor is not able to show the variables' values at debug time. Additionally, I am not able to easily modify the JS code by adding console.log to display some variables values.

Here is how the code inside the file `did-jwt.js` look like:
e.verifyJWT=function(t,e){void0===e&&(e={resolver:null,auth:null,audience:null,callbackUrl:null,skewTime:null,});try{if(!e.resolver)thrownewError('NoDIDresolverhasbeenconfigured');varr=G(t),n=r.payload,i=r.header,o=r.signature,a=r.data;returnPromise.resolve((function(t,e,r,n){try{vari=H[e];if(!i||0===i.length)thrownewError('Nosupportedsignaturetypesforalgorithm'+e);returnPromise.resolve(t.resolve(r)).then(function(t){console.log(t);if(!t)thrownewError('UnabletoresolveDIDdocumentfor'+r);varo=function(t,e){varr=t.publicKey.filter(function(t){returne===t.id;});returnr.length>0?r[0]:null;},a=t.publicKey||[];n&&(a=(t.authentication||[]).map(function(e){return'string'==typeofe?o(t,e):'string'==typeofe.publicKey?o(t,e.publicKey):e;}).filter(function(t){returnnull!=t;}));vars=a.filter(function(t){vare=t.type;returni.find(function(t){returnt===e;});});if(n&&(!s||0===s.length))thrownewError('DIDdocumentfor'+r+'doesnothavepublickeyssuitableforauthenticatinguser');if(!s||0===s.length)thrownewError('DIDdocumentfor'+r+'doesnothavepublickeysfor'+e);return{authenticators:s,issuer:r,doc:t};});}catch(t){returnPromise.reject(t);}})(e.resolver,i.alg,n.iss,e.auth)).then(function(r){vars=r.doc,f=r.issuer;returnPromise.resolve(V({header:i,data:a,signature:o},r.authenticators)).then(function(r){vari=Math.floor(Date.now()/1e3),o=e.skewTime>=0?e.skewTime:300;if(r){vara=i+o;if(n.nbf){if(n.nbf>a)thrownewError('JWTnotvalidbeforenbf:'+n.nbf);}elseif(n.iat&&n.iat>a)thrownewError('JWTnotvalidyet(issuedinthefuture)iat:'+n.iat);if(n.exp&&n.exp<=i-o)thrownewError('JWThasexpired:exp:'+n.exp+'<now:'+i);if(n.aud){if(!e.audience&&!e.callbackUrl)thrownewError('JWTaudienceisrequiredbutyourappaddresshasnotbeenconfigured');if(void0===(Array.isArray(n.aud)?n.aud:[n.aud]).find(function(t){returne.audience===t||e.callbackUrl===t;}))thrownewError('JWTaudiencedoesnotmatchyourDIDorcallbackurl');}return{payload:n,doc:s,issuer:f,signer:r,jwt:t};}});});}catch(t){returnPromise.reject(t);}}

Thanks in advance,

**Comment by jasonhealy** [comment]
Hi,  Thanks for reporting. Seems like an issue with `did-jwt`? If so can you open this issue directly in the `did-jwt` repo?  

https://github.com/decentralized-identity/did-jwt

Thanks

**Comment by Muhammad-Altabba** [comment]
Yes, you are right.
Thanks, and sorry for any inconvenience.
