### ISSUE TITLE
nacl-did IdentityController

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/veramo#57]
We need [nacl-did](https://github.com/uport-project/nacl-did) `IdentityController`.

It should be very similar to [daf-ethr-did-fs](https://github.com/uport-project/daf/blob/master/packages/daf-ethr-did-fs/src/identity-controller.ts), meaning it should save identity information in a plaintext json file.

Todo:
- [x] Copy `packages/daf-ethr-did-fs` to `packages/daf-nacl-did-fs`
- [x] Replace `ethr-did` with `nacl-did`
- [x] Add reference to the new package in `packages/tsconfig.json`, `packages/daf-cli/tsconfig.json` and `packages/daf-cli/package.json`
- [x] Add this new controller in [daf-cli setup](https://github.com/uport-project/daf/blob/master/packages/daf-cli/src/setup.ts#L50)

If everything goes well, you should be able to call `yarn daf identity-manager -c` and create new `nacl-did` identity.

**Comment by rado0x54** [comment]
Hey @simonas-notcat, I implemented the file-system controller in a branch. However, I'm still unsure about the `issuerFromIdentity` from identity part. See comments [in code](
https://github.com/uport-project/daf/blob/86a14cb893f210701902ce1dce5ad9d713a8ba99/packages/daf-nacl-did-fs/src/identity-controller.ts#L32).

Should I make the Signer definition more generic to allow Unit8Array or do map the signature into a string-compliant format?

Other things should be done.

**Comment by simonas-notcat** [comment]
Hey @rado0x54, you are right that there is a problem with `Signer` interface. We are currently working on fixing this. I would suggest that you create a work-in-progress PR for your branch, and we can come back to solving that last issue when the interfaces are settled.

**Comment by rado0x54** [comment]
Ok, I've created https://github.com/uport-project/daf/pull/60 so far.
