### ISSUE TITLE
decode JWT helper function

### ISSUE THREAD

**Issue by RobertoSnap** [uport-project/veramo#586]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i need to decode JWT, explicit checking and typing result.

**Describe the solution you'd like**
A one line function to decodeJWT with some options for verifying payload.
```ts
  async decodeJWT<CredentialType>(jwt: string, verifyOptions?: VerifyOptions) : DecodeJWTResult {
    // check signature
    // decode payload
    // check payload against verifyOptions
    // If this is a VP, decode all underlying VCs
  }
```
## types
Add some type help, you probably already have better types for this. Should have a type-guard to determine if one is working with a VP or VC. 

```ts
type DecodeJWTResult = VerifiableCrendentialPayload | VerifiablePresentationPayload 

type VC =  {
  "@context":  Array<string>
  "type": Array<string>
  sub: string,
  nbf: string
  iss: string
  aud: Array<string>
}
interface VerifiableCrendentialPayload extends VC {
  credentialSubject: Record<string, any>
  ...
}

interface VerifiablePresentationPayload extends VC {
  verifiableCredential/* ("s?") */: VerifiableCrendentialPayload[]
  ...
}
```

### Generic CredentialType
Able to pass in expected credential subject type which types into the credential subject of VC( or VCs of VP). Should type as a Partial(?) if we cant check the value against type at runtime.

## verifyOptions
I find this verify helpers easy to work with: https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback

> 

* `algorithms`: List of strings with the names of the allowed algorithms. For instance, `["HS256", "HS384"]`.
* `audience`: if you want to check audience (`aud`), provide a value here. The audience can be checked against a string, a regular expression or a list of strings and/or regular expressions. 
  > Eg: `"urn:foo"`, `/urn:f[o]{2}/`, `[/urn:f[o]{2}/, "urn:bar"]`
* `complete`: return an object with the decoded `{ payload, header, signature }` instead of only the usual content of the payload.
* `issuer` (optional): string or array of strings of valid values for the `iss` field.
* `jwtid` (optional): if you want to check JWT ID (`jti`), provide a string value here.
* `ignoreExpiration`: if `true` do not validate the expiration of the token.
* `ignoreNotBefore`...
* `subject`: if you want to check subject (`sub`), provide a value here
* `clockTolerance`: number of seconds to tolerate when checking the `nbf` and `exp` claims, to deal with small clock differences among different servers
* `maxAge`: the maximum allowed age for tokens to still be valid. It is expressed in seconds or a string describing a time span [vercel/ms](https://github.com/vercel/ms). 
  > Eg: `1000`, `"2 days"`, `"10h"`, `"7d"`. A numeric value is interpreted as a seconds count. If you use a string be sure you provide the time units (days, hours, etc), otherwise milliseconds unit is used by default (`"120"` is equal to `"120ms"`).
* `clockTimestamp`: the time in seconds that should be used as the current time for all necessary comparisons.
* `nonce`: if you want to check `nonce` claim, provide a string value here. It is used on Open ID for the ID Tokens. ([Open ID implementation notes](https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes))

Another option to say something about expected credential data would also be helpful. Throws if data is not present in the VC. Maybe this is possible to do with CredentialType as mentioned above.

If one send a VP with VCs, we want to check each VC against this options. Maybe a developer could optionally provide an map of verifyOptions {vpOptions: VerifyOptions, vcOptions: VerifyOptions}

Also, we sometimes need to check that the issuer of VP is the same as subject in credential, maybe this can be passed as a verifyOption.

**Describe alternatives you've considered**
Implementing it on our own, using 
- https://github.com/decentralized-identity/did-jwt/blob/ee8dbb45a5012e8c2b682aeb990f4e9dc1a7a6a4/src/JWT.ts#L176
- https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback

**Comment by mirceanis** [comment]
thanks for the suggestion!
This seems connected to the generalized verification API (#375)

**Comment by RobertoSnap** [comment]
Did a very simple, naive and dirty example here for testing:

```ts
  async decodeJWT(jwt: string, verifyOptions?: Partial<VerifyOptions>) {
    try {
      await this.verifyJWT(jwt);
      const payload = JSON.parse(Buffer.from(jwt.split('.')[1], 'base64').toString()) as JwtPayload;
      const errors = [];
      try {
        const isVP = 'vp' in payload && payload.vp.type.includes('VerifiablePresentation');
        if (verifyOptions.requireVerifiablePresentation && !isVP) {
          throw Error('JWT is not a VerifiablePresentation, expected a JWT with vp property and VerifiablePresentation in vp.types ');
        }
        if (verifyOptions.decodeCredentials) {
          if (!Array.isArray(payload.vp.verifiableCredential)) errors.push(`JWT vp.verifiableCredential was ${typeof payload.vp.verifiableCredential}, expected Array`);
          const decodedVerifiableCredentials = await Promise.all(
            payload.vp.verifiableCredential.map(async (subJWT) => {
              try {
                // Decode sub credential with overridden options,
                // REVIEW Is it correct to make sure VP issuer is subject of VC?
                const decoded = await this.decodeJWT(subJWT, {
                  ...verifyOptions,
                  decodeCredentials: false,
                  audience: undefined,
                  subject: payload.vp.iss,
                  requireVerifiablePresentation: false,
                });
                return decoded;
              } catch (error) {
                errors.push(`Error decoding subcredential: ${error.message}. \nSubcredential was: \n${Buffer.from(subJWT.split('.')[1], 'base64').toString()}`);
              }
            }),
          );
          payload.vp.jwts = decodedVerifiableCredentials;
        }
      } catch (error) {
        errors.push(`JWT was a Verifiable Presentation, error while decoding subcredential: ${error.message}`);
      }

      if (verifyOptions) {
        if (verifyOptions.audience) {
          if (typeof payload.aud === 'string') {
            if (payload.aud !== verifyOptions.audience) errors.push(`JWT audience was ${payload.aud}, expected ${verifyOptions.audience}`);
          } else if (Array.isArray(payload.aud)) {
            if (!payload.aud.includes(verifyOptions.audience)) errors.push(`JWT audience was ${payload.aud.join(' | ')}, expected one of ${verifyOptions.audience}`);
          } else {
            throw Error(`JWT .aud expected string or Array, got ${typeof payload.aud}`);
          }
        }
        if (verifyOptions.issuer) {
          if (typeof payload.iss !== 'string') throw Error(`JWT issuer expected string, got ${typeof payload.iss}`);
          if (typeof verifyOptions.issuer === 'string') {
            if (payload.iss !== verifyOptions.issuer) errors.push(`JWT issuer was ${payload.iss}, expected ${verifyOptions.issuer}`);
          } else if (Array.isArray(verifyOptions.issuer)) {
            if (!verifyOptions.issuer.includes(payload.iss)) errors.push(`JWT issuer was ${payload.iss}, expected one of ${verifyOptions.issuer.join(' | ')}`);
          } else {
            errors.push(`verifyOptions.issuer was ${typeof verifyOptions.issuer}, expected Array or string`);
          }
        }
        if (verifyOptions.subject) {
          if (payload.sub !== verifyOptions.subject) errors.push(`JWT subject was ${payload.sub}, expected ${verifyOptions.subject}`);
        }
      }
      if (errors.length > 0) throw Error(errors.join('.\n'));
      return payload;
    } catch (error) {
      console.log('Cant decode JWT => ', error.message);
      throw error;
    }
  }
}
```
types
```ts
export interface VerifyOptions {
  audience: string;
  complete: boolean;
  issuer: string | string[];
  ignoreExpiration: boolean;
  ignoreNotBefore: boolean;
  subject: string;
  decodeCredentials: boolean;
  requireVerifiablePresentation: boolean;
}

export interface JwtPayload {
  [key: string]: any;
  iss?: string;
  sub?: string;
  aud?: string | string[];
  exp?: number;
  nbf?: number;
  iat?: number;
  jti?: string;
}
```
