### ISSUE TITLE
Implement DIDComm support for multiple recipients

### ISSUE THREAD

**Issue by awoie** [uport-project/veramo#603]
In DIDComm, the `to` property is defined as an array. The property is OPTIONAL and if omitted, the recipient should assume that it is the intended recipient. If multiple recipients are provided, the recipient should assume that it is similar to an email CC message.

**Comment by mirceanis** [comment]
relevant code: https://github.com/uport-project/veramo/blob/78836a46d3ce71b568acaa98558b64f9c2b98167/packages/did-comm/src/didcomm.ts#L271
