### ISSUE TITLE
Add `exactMatch` option to DIDDiscovery

### ISSUE THREAD

**Issue by awoie** [uport-project/veramo#609]
The current version of DIDDiscovery potentially lead to wrong results, bob vs bobby, would result in two DIDs. That might be ok in some situations but would require to do extra validation of the result. 

We should add an `exactMatch` option to the `discoverDid` function in addition to `query` to limit the results to accurate matches.

**Comment by mirceanis** [comment]
looks like a perfect candidate for the `options` parameter.
