### ISSUE TITLE
Support DIDComm Messaging attachments

### ISSUE THREAD

**Issue by awoie** [uport-project/veramo#612]
TBD: needs more refinement

Extend the current DIDCommMessage and Message interfaces to support DIDCommV2 attachments as defined here: https://identity.foundation/didcomm-messaging/spec/#attachments

**Comment by codynhat** [comment]
I currently have a use case where `attachments` is needed. Currently, the [DIDCommMessageHandler](https://github.com/uport-project/veramo/blob/next/packages/did-comm/src/message-handler.ts#L101-L110) drops the `attachments` header before forwarding any unpacked messages. I am interested in taking on this work and opening a PR.

A little more context about my use case. I am developing a set of DIDComm protocols that will use the [IPLD](https://ipld.io) [DAG-JSON](https://ipld.io/docs/codecs/known/dag-json/) codec as a way to specify links to other content-addressable content. This content could be external to the DIDComm message, or can be an attachment in the message. I would like to be able to handle these attachments using Veramo, and also develop a new message handler that does the following:
1. Decodes a DIDComm `body` from the DIDCommMessageHandler as DAG-JSON, essentially turning links into `CID` objects
2. Packages the `body` and all `attachments` into an in-memory [CAR](https://ipld.io/specs/transport/car/) as the `raw` field on the `Message`

Message handlers specific to these DIDComm protocols that use DAG-JSON can then use IPLD tooling internally to traverse the message and its links to attachments using the CAR.

Here is an example of what a message using DAG-JSON and some attachments would look like:
```json
{
    "id": "...",
    "type": "...",
    "body": {
        "someLinkedContent": { "/": "<CID of offer>" },
    },
    "attachments": [
        {
          "data": {
            "hash": "<multi hash of content>"
            "json": {
              ... some attached JSON content
            }
          }
        }
    ]
}
```
