### ISSUE TITLE
What is the best way to ad custom columns to Claims and Credentials

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/veramo#645]
Hello,
We are using the Web DID method. And we need to have custom columns to save for example the relevant id of the claim that exists in our centralized system. And another column to indicate if the credential is supposed to be publicly available through an endpoint that will list all public credentials (like the official website of the company for example).
What do you suggest for us to do? And are those columns are this the best to be added to Claims or to Credentials? 
Thanks in advance,

**Comment by mirceanis** [comment]
Hi @Muhammad-Altabba,
Are these custom claims embedded in the credentials? If they are, you don't need any modification to the database layout. They can be matched using the existing @veramo/data-store API.

Also, the DID method that you use should not matter for this.
