### ISSUE TITLE
dataStoreDeleteVerifiableCredential will fail when the TypeORM is not using "default" name

### ISSUE THREAD

**Issue by rtang03** [uport-project/veramo#649]
When the TypeORM is using connection name, other than "default"; the dataStoreDeleteVerifiableCredential will fail. 

See
https://github.com/uport-project/veramo/blob/next/packages/data-store/src/data-store.ts#L71

```
claims.forEach(async (claim) => {
      await claim.remove()
    })
```

It will throw below error
```
(node:65158) UnhandledPromiseRejectionWarning: RepositoryNotFoundError: No repository for "Claim" was found. Looks like this entity is not registered in current "default" connection?
```

Like previous code snippet, it should use `await (await this.dbConnection)` to getRepository, to remove corresponding claims.

**Comment by mirceanis** [comment]
Good catch, are you willing to contribute a fix?

**Comment by rtang03** [comment]
The fix is easy. But I may not have proper environment to test it well.

Here is fix for your consideration:

```
    // BEFORE
    // claims.forEach(async (claim) => {
    //   await claim.remove()
    // })

    // AFTER
    await (await this.dbConnection).getRepository(Claim).remove(claims);
```
