### ISSUE TITLE
React native: Veramo requires @mattrglobal/node-bbs-signatures which does not compile on RN (without expo)

### ISSUE THREAD

**Issue by RobertoSnap** [uport-project/veramo#664]
**Bug severity**
3

**Describe the bug**
Trying to get Veramo running on React native, getting `Error: Unable to resolve module @mattrglobal/node-bbs-signatures``
Tried installing it explicit,  but then it fails to compile with call to undefined module  

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone **branch veramoProvider** https://github.com/symfoni/identity-wallet/tree/veramoProvider
2. npm install
3. npm run ios
4. See error:  Error: Unable to resolve module @mattrglobal/node-bbs-signatures
5. npm i @mattrglobal/node-bbs-signatures --save
6. See error: `Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`. 
VeramoProvider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.identityWallet:263487:41
ContextProvider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.identityWallet:139237:41` See image below.

**Observed behaviour**
A clear and concise description of what you observe.
   
**Expected behaviour**
Could BBS-signatures be optional? Else, any had this issue before and a way to either get it working or circumvent it for now.

**Details**
Error without BBS signatures
![12-08-2021 at 13 26 00](https://user-images.githubusercontent.com/4772930/129189144-855aa1c7-49f6-4436-9ddc-e7cda69ca1ea.png)
Error after installing BBS signatures
![12-08-2021 at 13 36 21](https://user-images.githubusercontent.com/4772930/129190422-811606d5-7280-4980-87b9-5f4dc9eda3b0.png)

**Versions (please complete the following information):**
 -     "@veramo/core": "^2.1.0",
    "@veramo/credential-w3c": "^2.1.0",
    "@veramo/data-store": "^2.1.0",
    "@veramo/did-jwt": "^2.1.0",
    "@veramo/did-manager": "^2.1.0",
    "@veramo/did-provider-ethr": "^2.1.0",
    "@veramo/did-provider-key": "^2.1.0",
    "@veramo/did-resolver": "^2.1.0",
    "@veramo/key-manager": "^2.1.0",
    "@veramo/kms-local": "^2.1.1",
    "@veramo/message-handler": "^2.1.0",
    "@veramo/selective-disclosure": "^2.1.0",
 - "react-native": "0.64.1",
 - "rn-nodeify": "^10.3.0",
 -  "node-libs-react-native": "^1.2.1",

**Comment by mirceanis** [comment]
This is strange. That dependency should not be required in this version of veramo. Can you list the dependencies and devdependencies you have in package.json?

**Comment by RobertoSnap** [comment]
Looks like @veramo/did-provider-key@2.1.0 has the dependecy?

![13-08-2021 at 10 40 43](https://user-images.githubusercontent.com/4772930/129330601-ef10181a-5e51-47ec-8b02-058c64b37066.png)

**Comment by mirceanis** [comment]
great find!
I suppose it's ok to exclude that provider if you are not using it. It's not a core element.

**Comment by RobertoSnap** [comment]
We are useing @veramo/did-provider-key for some services and without it we cant resolves does DIDs in the react native client. So its actually a blocker for us.

We could port those services to Ethr, but have a problem there as described in https://github.com/uport-project/veramo/issues/677
