### ISSUE TITLE
eth-did-provider in-flexible network property

### ISSUE THREAD

**Issue by RobertoSnap** [uport-project/veramo#677]
**Bug severity**
4

**Describe the bug**
When settin up a DIDManager with ethr. Network is constrained by the EthrDidProvider.constructur where network must be a string for the most used networks. 

We are useing Arbitrum, thereby not supported.

```ts
new DIDManager({
            store: new DIDStore(dbConnection),
            defaultProvider: "did:ethr:eip155:421611",
            providers: {
                "did:ethr:eip155:421611": new EthrDIDProvider({
                    defaultKms: "local",
                    network: "rinkeby", // ERROR, i would prefer not to input this or set it to eip155:421611
                    rpcUrl: "https://arbitrum-rinkeby.infura.io/v3/XXXXXXXXXXXXXX",
                    registry: "0x8f54f62CA28D481c3C30b1914b52ef935C1dF820",
                }),
            },
        }),
        
```

**To Reproduce**
Setup an agent config with DIDManager.

**Expected behaviour**
Expect it to either accept a ethers.networkish parameter or nothing if it can be infered from something else like web3provider or rpcUrl.

**Details**

![test]( https://user-images.githubusercontent.com/4772930/130641670-e64a7241-dbc6-496e-b896-c88ea8a209a1.png)

![](https://user-images.githubusercontent.com/4772930/130641836-5a52397c-7cc4-4f84-88fa-a0e9d3ea61bf.png)

**Versions (please complete the following information):**
    "@veramo/core": "^2.1.0",
    "@veramo/credential-w3c": "^2.1.0",
    "@veramo/data-store": "^2.1.0",
    "@veramo/did-jwt": "^2.1.0",
    "@veramo/did-manager": "^2.1.0",
    "@veramo/did-provider-ethr": "^2.1.0",
    "@veramo/did-resolver": "^2.1.0",
    "@veramo/key-manager": "^2.1.0",
    "@veramo/kms-local": "^2.1.1",
    "@veramo/message-handler": "^2.1.0",
    "@veramo/selective-disclosure": "^2.1.0",

**Comment by mirceanis** [comment]
@RobertoSnap As a potential workaround, can you try to set the network to "0x66eeb"?
If it doesn't, try
```ts
  network: 421611 as unknown as number
```
to try to punch through the limited data type we've got now.

**Comment by RobertoSnap** [comment]
Yea, seems to work 👍

**Comment by RobertoSnap** [comment]
Dident work in our nodejs enviroement with nestJS :(

**Comment by RobertoSnap** [comment]
Or it works, but does not seem to be able to resolve correctly. 

Im getting `Error: Unsupported message type` which i think is the same as what happend here: https://github.com/uport-project/veramo/discussions/579

**Comment by RobertoSnap** [comment]
Ahh, wait, it was a Infura Outage on Rinkeby Arbitrum. So it probably works
