### ISSUE TITLE
Add support for EthWallets as KMS

### ISSUE THREAD

**Issue by awoie** [uport-project/veramo#688]
IdentityManager has an import function and it would be good to have the ability to import DIDs that have keys that are managed by EthWallets (e.g., MetaMask). This is required to support did:ethr and did:ens using Blockchain Accounts that are only managed in an EthWallet.

Key operations that will be required are likely eth_signTransaction (for updating ENS records), and signTypedData for EthereumEip712Signature2021 to issue VCs etc.

**Comment by simonas-notcat** [comment]
Initial code:

https://github.com/veramolabs/walletconnect-test-wallet/blob/did/src/controllers/plugins/did-store.ts
https://github.com/veramolabs/walletconnect-test-wallet/blob/did/src/controllers/plugins/key-store.ts
