### ISSUE TITLE
Please provide an example how to create a VerifiableCredential

### ISSUE THREAD

**Issue by martijndebruijn** [uport-project/veramo#736]
The current example show how to create a DID. Examples about how to create a VC and VP are missing. 
Adding these examples would be of great help.

**Comment by mirceanis** [comment]
A great source of examples is the integration test-suite ([`./__tests__/`](https://github.com/uport-project/veramo/blob/next/__tests__)).
[Here is an example of creating a VC](https://github.com/uport-project/veramo/blob/c20a409d8bbc84bdd41809a722c1fd599707e46a/__tests__/shared/verifiableData.ts#L29), and [here's one for a VP](https://github.com/uport-project/veramo/blob/c20a409d8bbc84bdd41809a722c1fd599707e46a/__tests__/shared/verifiableData.ts#L118).

We value your contributions and feedback, so if you think these examples should be somewhere more specific, please raise an issue or, even better, create a pull request.

**Comment by martijndebruijn** [comment]
Thanks


E. ***@***.***
M. 06 - 55 713 186



Op ma 8 nov. 2021 om 10:54 schreef Mircea Nistor ***@***.***>:
