### ISSUE TITLE
[proposal] Adding a test/example for adding services with did:ethr

### ISSUE THREAD

**Issue by Ajmasta** [uport-project/veramo#748]
**Is your feature request related to a problem? Please describe.**
I keep getting error messages when I try to add services to a did:ethr. The tests include a nice template for didManagerAddService with a web did but it would be great to have one for ethr, as it's kind of a special case (I think, since I get problems related to gas and I have no idea what to do).

**Describe the solution you'd like**
The test could be adding one service, and then another test could be to fetch that one service, so that the whole process has a nice example in the docs. Also does adding services require gas?

**Describe alternatives you've considered**
This problem is clearly because I am a noob with veramo and DID in general, but I'm sure that many web devs would appreciate the little extra help, either in tests or in the docs directly. 

**Additional context**
I have completed the node.js tutorial to create DIDs, and it works great. I was having fun playing with them by adding various features, but I failed at services. 
Also thanks for all the great work. I knew nothing about DID 24 hours ago and now I am able to create one on the ETH blockchain, simply amazing.

**Comment by mirceanis** [comment]
Thank you for the proposal.
We recently [added an integration test suite](https://github.com/uport-project/veramo/blob/183b4bc5ca3dcf11dd111e7e1ae19636909ff4c7/__tests__/shared/didCommWithEthrDidFlow.ts#L164) that does that.
The suite uses a local ganache blockchain, but the calls to add the service would be the same for a public network.

The difference is that the DIDs used in the test have corresponding addresses that are pre-funded on ganache, so there are no gas issues.

The tests I linked to can be modified to require gas and show how to find the address that requires funding, etc.(and we very much appreciate contributions)
You would have to compute the address directly from the controller key, or resolve your newly created DIDs and get the address from the controller `blockchainAccountId` field you find in the resolved document.

I hope this helps.
If you come to a solution before we can update the tests/docs, please let us know with a PR, or open a discussion in [show and tell](https://github.com/uport-project/veramo/discussions/categories/show-and-tell)
Have fun with it!

**Comment by Ajmasta** [comment]
> Thank you for the proposal. We recently [added an integration test suite](https://github.com/uport-project/veramo/blob/183b4bc5ca3dcf11dd111e7e1ae19636909ff4c7/__tests__/shared/didCommWithEthrDidFlow.ts#L164) that does that. The suite uses a local ganache blockchain, but the calls to add the service would be the same for a public network.
> 
> The difference is that the DIDs used in the test have corresponding addresses that are pre-funded on ganache, so there are no gas issues.
> 
> The tests I linked to can be modified to require gas and show how to find the address that requires funding, etc.(and we very much appreciate contributions) You would have to compute the address directly from the controller key, or resolve your newly created DIDs and get the address from the controller `blockchainAccountId` field you find in the resolved document.
> 
> I hope this helps. If you come to a solution before we can update the tests/docs, please let us know with a PR, or open a discussion in [show and tell](https://github.com/uport-project/veramo/discussions/categories/show-and-tell) Have fun with it!

Thank you so much for the detailed answer.

I will play around with this and see if I can find some sort of solution. I can't promise anything though as I am way out of my comfort zone here.

**Comment by mirceanis** [comment]
Wonderful!

Don't worry about being out of your comfort zone. This stuff is not easy and our API is not always intuitive.
That being said, it is very useful for us to understand where the friction is and how we can improve.

Fresh eyes are valuable, so please feel free to share feedback and pain points.

Have fun!
