### ISSUE TITLE
[proposal] Use stable address/account as canonicalId in resolved DID Documents

### ISSUE THREAD

**Issue by csuwildcat** [uport-project/veramo#749]
**Is your feature request related to a problem? Please describe.**
Top-level names can expire or be detached from the user in other ways, so to ensure a continuance of connections and interactions with others who a person or entity has engaged with, it is best to use a stable Canonical ID.

**Describe the solution you'd like**
Output the stable account/address as the `canonicalId` in the resolved DID Document.

**Describe alternatives you've considered**
There are no other standard or reliable alternatives to this.

**Comment by mirceanis** [comment]
Thanks for the proposal!

Is there a way to map a DID to a canonicalId, that is an improvement to the result provided by the DID method resolver?

Or, perhaps I'm not understanding this issue enough. Can you provide some examples?

**Comment by csuwildcat** [comment]
The `canonicalId` field would just be set to a DID representation of the base account/address that owns the name (of which I believe there exists one), and using the `canonicalId` field in the DID Document instructs the resolving party to use that inside their systems to create associations instead of the top-level name. Think of names like your Twitter Display Name, and your actual canonical ID as the unchanging stable GUID in the Twitter db. This is probably just a safer paradigm in my opinion, because, if used properly, it should avoid cases where people lose their names and others can masquerade as them.

**Comment by mirceanis** [comment]
I think the reason why I'm still confused a bit is that veramo doesn't enforce a relationship between a name and a did, or between a did and an address.

There are addresses derived from keys that are linked to a did, and I suppose a relationship can be created between them and presented as canonical ID, but these addresses are not stored individually in a db (yet?..). They are just derived when required.

I still feel that I'm misunderstanding your request so if I'm way off base please correct me.

**Comment by csuwildcat** [comment]
@mirceanis I was made aware by @awoie that this may not be the right repo, and that there is one for ENS DIDs that this is more appropriate for. While I don't personally use ENS, I think it would be good for that method to anchor on canonical IDs that aren't subject to some of the issues I outlined.

**Comment by mirceanis** [comment]
Yes, that makes a lot more sense, and I agree!
I suppose this is the right repo for it: https://github.com/veramolabs/did-ens-spec
