### ISSUE TITLE
remote-server api-key-auth is broken

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/veramo#771]
`passport@0.5.0` introduced a breaking change. Because of it, when running `veramo server` you get this error:

`TypeError: req.logIn is not a function`

**Comment by iliecirciumaru** [comment]
Hey, thanks for fix! 
Are you going to make this fix a part of new version soon ?
It is a little bit of headache to have this bug still in 3.1.0

**Comment by mirceanis** [comment]
@iliecirciumaru I'll cherry pick this fix and release 3.1.1 soon.
