### ISSUE TITLE
Production build issue with migration file timestamp

### ISSUE THREAD

**Issue by rkreutzer** [uport-project/veramo#778]
**Bug severity**
3

**Describe the bug**
After compiling a production build (Ionic/Capacitor), then when the app attempts to createConnection to the database, the following error is returned. A development build works OK.

"migration name is wrong. Migration class name should have a JavaScript timestamp appended"

**To Reproduce**
Steps to reproduce the behaviour:
1. Build with --prod flag
2. Attempt to open the database

**Observed behaviour**
On createConnection: 
g:  migration name is wrong. Migration class name should have a JavaScript timestamp appended.
    at new g (http://localhost/main.9f7448e4642ebf0c79a3.js:1:3116881)
    at http://localhost/main.9f7448e4642ebf0c79a3.js:1:3149533
    at Array.map (<anonymous>)
    at qe.getMigrations (http://localhost/main.9f7448e4642ebf0c79a3.js:1:3149430)
    at qe.<anonymous> (http://localhost/main.9f7448e4642ebf0c79a3.js:1:3143521)
    at http://localhost/main.9f7448e4642ebf0c79a3.js:1:4118445
    at Object.next (http://localhost/main.9f7448e4642ebf0c79a3.js:1:4118552)
    at z (http://localhost/main.9f7448e4642ebf0c79a3.js:1:4117269)
    at P.invoke (http://localhost/polyfills.37dca26f56c14ea67b5d.js:1:36019)
    at Object.onInvoke (http://localhost/main.9f7448e4642ebf0c79a3.js:1:155879)
   
**Expected behaviour**
The db connection should be established

**Versions:**
 - Veramo: 3.1.0
 - Browser Chrome/Brave
 - Node Version 14.16.1

**Comment by mirceanis** [comment]
Thank you for posting about this.

This is not a bug in veramo, but rather a requirement of typeorm which is used by @veramo/data-store to abstract the database connection.

As a workaround, you can try to configure your build system to preserve the migration file names.

This issue from their repo might help https://github.com/typeorm/typeorm/issues/2164

Please check back with results as many more could benefit from your findings

**Comment by rkreutzer** [comment]
I agree that it's because uglifyjs is mangling the typeorm table names. This comment [issuecomment-495185024](https://github.com/typeorm/typeorm/issues/2164#issuecomment-495185024) from the link above show how to setup a config file to turn off mangling. 

I couldn't get it to work, so I turned off script optimization in the angular.json file for production builds, and that works.
