### ISSUE TITLE
Clicking the link README.md / Plugins Directory -> Gives 404 page

### ISSUE THREAD

**Issue by Arxcis** [uport-project/veramo#785]
**Bug severity**
1

**Describe the bug**
Hi I am looking for plugin-documentation, but when I click [the "Plugin Directory" link in the README.md](https://veramo.io/docs/veramo_agent/plugins_list) I get to a 404-page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [README.md](https://github.com/uport-project/veramo#veramo)
2. Click on [Plugins Directory](https://veramo.io/docs/veramo_agent/plugins_list)

**Observed behaviour**
404 page
   
**Expected behaviour**
Page documenting the plugins directory.

**Details**

| broken link | 404 page |
|----------|-----------|
| <img width="1009" alt="image" src="https://user-images.githubusercontent.com/3092618/146351254-6fb8dfb9-e4ff-4a0c-a774-05593674368e.png"> | <img width="1259" alt="image" src="https://user-images.githubusercontent.com/3092618/146351393-40243e99-3268-439f-8fcc-331834a75335.png"> | 

**Additional context**
Not relevant

**Versions (please complete the following information):**
Not relevant

**Comment by mirceanis** [comment]
Thank you for reporting this!

**Comment by Arxcis** [comment]
By the way, I also found that none of these links work:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/3092618/146353650-b58c6288-8bed-4770-912a-d66a59e84358.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/3092618/146353696-d14bced5-310a-4c59-aca5-fb30926d5087.png">

**More broken links**
- https://veramo.io/docs/guides/cli
- https://veramo.io/docs/guides/nodejs
- https://veramo.io/docs/guides/browser
- https://veramo.io/docs/guides/react_native
- https://veramo.io/docs/guides/create_plugin
- https://veramo.io/docs/guides/cloud_agent
