### ISSUE TITLE
add-service for a did:web returns `{ success: true }`, without doing anything?

### ISSUE THREAD

**Issue by Arxcis** [uport-project/veramo#786]
**Bug severity**
2

**Describe the bug**
- `veramo did add-service` for a did:web returns `{ success: true }`, without doing anything.
- #172 addressed this, but the issue was closed without an explanation or plan for implementation.
- The source code shows that the implementation of `addService` is a stub doing nothing (See: https://github.com/uport-project/veramo/blob/next/packages/did-provider-web/src/web-did-provider.ts#L52-L57)

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `veramo did create` and create a `did:web`.
```
 % veramo did create
(node:8798) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
? Select identifier provider did:web
? Select key management system local
? Enter alias symfoni.id
┌──────────┬────────────┬────────────────────┐
│ provider │      alias │                did │
├──────────┼────────────┼────────────────────┤
│  did:web │ symfoni.id │ did:web:symfoni.id │
└──────────┴────────────┴────────────────────┘
```
2. Run `veramo did add-service`
```
jonasjobb@jonass-iMac-2 veramoagent % veramo did add-service
(node:8802) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
? Select DID did:web:symfoni.id
? Service type DIDCommMessaging
? Endpoint symfoni.id/didcomm
? ID didcomm
Success: { success: true }
```

**Observed behaviour**
```
Success: { success: true }
```
But no service was added due to this command being a stub. (See: https://github.com/uport-project/veramo/blob/next/packages/did-provider-web/src/web-did-provider.ts#L52-L57)
   
**Expected behaviour**
```
Success: { success: true }
```
And expect a `DIDCommMessaging`-service to have been added to the `.well-known/did.json` DID-document.
```
% curl -H "host: symfoni.id" localhost:3332/.well-known/did.json
{}%
```
*Note:* I receive the empty object {} here, because of another issue I have, which I here: https://github.com/uport-project/veramo/issues/784#issuecomment-995671074.

**Details**
null

**Additional context**
null

**Versions (please complete the following information):**
 - Veramo: `3.1.0`
 - Node Version: `v14.18.1`

**Comment by mirceanis** [comment]
Thank you for reporting this.

Actually, in the case of `did:web`, most of the logic for adding the Key/Service is [in the base plugin `@veramo/did-manager`](https://github.com/uport-project/veramo/blob/5202ef1dd51fd3b7ad57591fd726fdc571bc8492/packages/did-manager/src/id-manager.ts#L177)

It is the DID manager that maintains the internal mapping between DID and Keys/Services and then this internal mapping is used by the [`web-did-doc-router`](https://github.com/uport-project/veramo/blob/5202ef1dd51fd3b7ad57591fd726fdc571bc8492/packages/remote-server/src/web-did-doc-router.ts#L33) to construct a DID document to be served.

There is not much other logic to be added to the `@veramo/did-provider-web` since most things are already covered.

There is a fix available on the `next` distTag that will help you get the full DID document when you use the `curl` command like that.
You can either `yarn global add @veramo/cli@next`
or start the `@next` server directly through npx: `npx @veramo/cli@next server`

If you think this answer is enough, please close the issue. Otherwise, please elaborate on proposed improvements.

**Comment by Arxcis** [comment]
Yes. Perfect. This issue is a non-issue. Everything works as expected, once I was able to actually verify it by running `@veramo/cli@next`:
```
% veramo --version
3.1.1-next.19

% veramo server

% curl -H "host: symfoni.id" localhost:3332/.well-known/did.json
{"@context":"https://w3id.org/did/v1","id":"did:web:symfoni.id","verificationMethod":[{"id":"did:web:symfoni.id#0473743882e12ba70f74eb22d0936a907a9d1bcf13c2bfd6822d60b09c04d1c5175c389fee75c83b05ca0759431c3c80b3a5936ea347bbca758c5b865a0c836652","type":"EcdsaSecp256k1VerificationKey2019","controller":"did:web:symfoni.id","publicKeyHex":"0473743882e12ba70f74eb22d0936a907a9d1bcf13c2bfd6822d60b09c04d1c5175c389fee75c83b05ca0759431c3c80b3a5936ea347bbca758c5b865a0c836652"}],"authentication":["did:web:symfoni.id#0473743882e12ba70f74eb22d0936a907a9d1bcf13c2bfd6822d60b09c04d1c5175c389fee75c83b05ca0759431c3c80b3a5936ea347bbca758c5b865a0c836652"],"assertionMethod":["did:web:symfoni.id#0473743882e12ba70f74eb22d0936a907a9d1bcf13c2bfd6822d60b09c04d1c5175c389fee75c83b05ca0759431c3c80b3a5936ea347bbca758c5b865a0c836652"],"keyAgreement":[],"service":[{"id":"didcomm","type":"DIDCommMessaging","serviceEndpoint":"symfoni.id/didcomm","description":null}]}% 
```

This issue was raised due to ME not fully grasping how the plugin architecture in Veramo works. I turns out that default behavior is running in the  [base plugin](https://github.com/uport-project/veramo/blob/5202ef1dd51fd3b7ad57591fd726fdc571bc8492/packages/did-manager/src/id-manager.ts#L177) before (or after?) the special code of a specific plugin. If a plugin does nothing but return:
```
{ success: true }
```
It does NOT mean that the plugin does nothing. It just means that whatever the base-plugin is doing is enough, and not specialized code is needed, am I correct  @mirceanis? 🤔

**Comment by mirceanis** [comment]
> Yes. Perfect. This issue was a non-issue. Everything works as expected,

Wonderful!

> It does NOT mean that the plugin does nothing. It just means that whatever the base-plugin is doing is enough, and no specialized code is needed, am I correct @mirceanis? 🤔

Yes that is correct :)
