### ISSUE TITLE
[BUG] credential-ld module uses require('fs') which limits the platforms where it can be used

### ISSUE THREAD

**Issue by mirceanis** [uport-project/veramo#837]
This is used to load `@context` objects asynchronously.
This should be replaced by another mechanism that also works in browser environments.

**Comment by pcibraro** [comment]
It is not working either in node.js. It is trying to pull the default context files in LdDefaultContexts from the contexts directory, and that directory is not available under the node_modules when it is installed through npm.

**Comment by mirceanis** [comment]
Right, we need a better method of loading the default contexts.

In the worst case scenario, they would be hard-coded JSON objects, part of the source code, but perhaps we can come up with something better.

Suggestions are welcome :)

**Comment by pcibraro** [comment]
Yes, I guess you can also import them in the main file as dependencies or provide a kind of resolver if you don't to include them in your module.

Thanks
