### ISSUE TITLE
Hi everyone, i want to ask something related to '@veramo/remote-server'  this lib.

### ISSUE THREAD

**Issue by vijay05155** [uport-project/veramo#891]
Hi everyone, i want to ask something related to '@veramo/remote-server'  this lib.

i was hosted a server using this code that was mention in veramo.io,

import express from 'express'
import { agent } from './agent'
import { AgentRouter, ApiSchemaRouter, WebDidDocRouter } from '@veramo/remote-server'

const getAgentForRequest = async (req: express.Request) => agent
const exposedMethods = agent.availableMethods()
const basePath = '/agent'
const schemaPath = '/open-api.json'

const agentRouter = AgentRouter({
  getAgentForRequest,
  exposedMethods,
})

const schemaRouter = ApiSchemaRouter({
  basePath,
  getAgentForRequest,
  exposedMethods,
})

const didDocRouter = WebDidDocRouter({
  getAgentForRequest,
})

const app = express()
app.use(basePath, agentRouter)
app.use(schemaPath, schemaRouter)
app.use(didDocRouter)
app.listen(3002),

but when i try to use "http://localhost:3002/open-api.json"  this address in postman i got , "agent not avilable"  in response, can you please help me.

_Originally posted by @vijay05155 in https://github.com/uport-project/veramo/discussions/733#discussioncomment-2799055_

**Comment by mirceanis** [comment]
Hi @vijay05155, did you get an answer to your question?

If you did and if you think it would help someone else, please consider describing your solution here :)
