### ISSUE TITLE
[proposal] Define a credential revocation API

### ISSUE THREAD

**Issue by mirceanis** [uport-project/veramo#937]
We need a plugin interface for the credential revocation frontend.

At this time, there are 2 foreseeable actions that this interface should perform:

* One is a call to revoke a credential. Probably this interface will be implemented by an aggregator that can look at a credential that is about to be revoked, inspect the `credentialStatus` entry and then forward the revocation call to the actual credentialStatus driver.

* The other (which may be optional?) is a call that a Credential Issuer might make to build a `credentialStatus` entry.
Many credentialStatus methods work on collections of credentials, so it is likely that when a credential is being created it needs to know its place in the collection (its index, its merkle path, etc)

This task only refers to the interface for such a plugin, and should initially serve as a discussion board.

**Comment by italobb** [comment]
In the picture below, in yellow, we have the current components already implemented when we talk about credential revocation/status in Veramo. In green, a proposal for the components we should build to allow two initial revocation methods: one using local storage (it can implement [Revocation List 2020](https://w3c-ccg.github.io/vc-status-rl-2020/) or a simpler spec) and another one using an EVM network (following the [ethr-status-registry](https://github.com/uport-project/ethr-status-registry)).

![image](https://user-images.githubusercontent.com/1801687/173910062-78340138-9651-472b-b77d-c6e6562602a1.png)

Here is a brief explanation about each component in the diagram:
- `credential-revocation`: implements the interface mentioned by @mirceanis for the revocation and delegates their implementation to plugin specific for each revocation method.
- `revocation-plugin`: an interface for revocation methods plugins.
- `revocation-eth`: a revocation plugin which uses the [ethr-status-registry](https://github.com/uport-project/ethr-status-registry) spec.
- `revocation-local`: a revocation plugin which uses [Revocation List 2020](https://w3c-ccg.github.io/vc-status-rl-2020/) or a simpler method for revocation, storing the status using the agent `data-store`. This component, exceptionally, will also be used by the agent to serve the endpoint used in `credentialStatus` field of the VCs using the revocation method chosen.
- `credential-status-eth`: a library which implements the status verification using [ethr-status-registry](https://github.com/uport-project/ethr-status-registry).
- `revocation-eth`: a library which implements the revocation of VCs using the  [ethr-status-registry](https://github.com/uport-project/ethr-status-registry).

As suggested by @mirceanis, the `credential-revocation` will expose 2 main endpoints:
- `revoke`
    - Params: 
        - `vc`: a reference to the VC to be revoked.
        - `method`: a reference to the revocation method to be used
        - `method-params` (optional): a JSON object with the revocation method params, if necessary.
    -  Return: 
        - The updated revocation status
- `metadata`
    - Params:
        - `method`: a reference to the revocation method
    -  Return:
        - A JSON describing the params for the revocation method (the params received as input in `revoke`.`method-params`).

The `revocation-local` plugin will additionally implement the endpoint referenced in the `credentialStatus` field of the VCs using the method [Revocation List 2020](https://w3c-ccg.github.io/vc-status-rl-2020/) or a simpler one TBD in this discussion:
- `status`
    - Params:
        - `vc`: a reference to the VC to be revoked.
    - Return:
        - The credential status. In case we decide to use [Revocation List 2020](https://w3c-ccg.github.io/vc-status-rl-2020/), it'll be the a VC following the [`RevocationList2020Credential`](https://w3id.org/vc-revocation-list-2020/v1) schema.

In addition to a feedback regarding this proposal, it would be nice to understand if there are more revocation methods already specified and implemented in libraries which we could plug or adopt, mainly for the local (initial) implementation.

**Comment by italobb** [comment]
@mirceanis I liked all suggestions, including the naming. Your understanding about the `metadata` was wrong, but I realized that the endpoint to query the parameters for a revocation method doesn't make sense. So, the `credentialStatusGenerate` is fine. Actually we'll need an endpoint to list the supported revocation methods in the agent.

So, we would have something like:

- `credentialStatusUpdate` - updates the status of an existing credential
    - Params:
        - vc: a reference to the VC to be revoked.
        - options (optional): a JSON object with the revocation method specific params, if necessary.
    - Return:
        - `result`: JSON object
            - `success`: boolean telling if the request was successfully processed (doesn't mean the revocation was completed yet)
            - `error`: string with error details.
            - `details`: JSON with optional details provided by the revocation driver specific to the revocation method.
- `credentialStatusGenerate ` - generates the `credentialStatus` property for future credentials
    - Params:
        - `method`: The name of the revocation method
        - `options` (optional): parameters specific to the revocation method
    - Return:
        - `credentialStatus `: the credentialStatus property for future credentials
-  `credentialStatusRead `:  returns the status of a particular credential, as it is known by this agent.
-  `credentialStatusListMethods`:  returns the list of revocation methods supported by the agent.

**Comment by Eengineer1** [comment]
Hey, @italobb @mirceanis .

Keen on helping with this.
A few questions:

- Have any implementations started on this?
- What's the bandwidth?

**Comment by italobb** [comment]
Hi, @Eengineer1! 
I'm currently writing the interfaces we just described here and planning the implementation of the components for next Veramo version. It's the right time to have you joining! 
Do you have something specific you want to collaborate on? It would be nice to get together to plan. Could you please get in touch with me through the Veramo Discord channel, please?

**Comment by Eengineer1** [comment]
@italobb Thanks!
You have PM.
