### ISSUE TITLE
DIDComm pack message support for Aries RFC 0019

### ISSUE THREAD

**Issue by rkreutzer** [uport-project/veramo#950]
The current DIDComm pack (and unpack?) message routines don't support the encryption envelope format specified in [Aries RFC 0019](https://github.com/hyperledger/aries-rfcs/tree/main/features/0019-encryption-envelope). Is this planned as another type of authcrypt/anoncrypt?

I'm glad to contribute, I just need some direction.

**Comment by mirceanis** [comment]
Actually, we had this in a previous version of veramo.
The differences from what we have today are subtle.
The encryption I think is the same, at least for anoncrypt, but we mark it differently in the resulting JWE, to be closer to the more recent did-comm spec.
(we don't use `JWM/1.0` for `typ`, nor `authcrypt` / `anoncrypt` for `alg`)

We didn't have any bandwidth yet to consider extending our implementation to support this format too, but I'm open to suggestions.

**Comment by rkreutzer** [comment]
After more research, it doesn't make sense for me to try to support something older. I was trying to support the examples at try.connect.me, but I'll let them catch up to the current spec.
