### ISSUE TITLE
[chore] clarify credential-status method names

### ISSUE THREAD

**Issue by mirceanis** [uport-project/veramo#981]
Based on a discussion from a previous issue(https://github.com/uport-project/veramo/pull/956#issuecomment-1206160383):

---

We have the `CredentialStatus` data type defined in `vc-data-model.ts` and we also use the `CredentialStatus` type from the `credential-status` library under the name `CredentialStatusVerification`. It's a bit confusing, IMO.

While this feature is fresh and there are not many backward compatibility issues, what do you think about renaming some of them for a bit more clarity?

I propose naming them like this:
`CredentialStatus` -> `CredentialStatusCoordinates` for the property that gets embedded in the VC
`CredentialStatusVerification` -> `CredentialStatus` for the current status of the credential

@italobb proposed `CredentialStatusReference` instead of `CredentialStatusCoordinates`

This should be done before the v4 release.

**Comment by mirceanis** [comment]
Also, on the same subject, the plugin interfaces should be aligned.

`ICredentialStatus`, defined in `core`, `ICheckCredentialStatus` defined in `credential-status` is a little confusing.
Also, their names don't suggest that one is ONLY for generating/managing status and another one is for verification

Let's define both of these interfaces in `core` and align their names too.

I propose `ICredentialStatusManager` && `ICredentialStatusVerifier`
(and together they could form a single interface called `ICredentialStatus`)

@italobb what do you think?

**Comment by italobb** [comment]
@mirceanis Much more clear, for sure.
